site_name: My Docs
site_author: 始于迁至

google_analytics: ['UA-36723568-3', 'mkdocs.org']

repo_name: 'Msl GitHub'
copyright: "Copyright 2024 始于迁至"

docs_dir: 'docs'

theme:
  name: 'material'
  language: 'zh'  
  palette: 
    primary: 'light blue'
    accent: 'indigo'
  feature:
    tabs: true; 